// Generated by CoffeeScript 1.3.1
var Config;

Config = (function() {

  Config.name = 'Config';

  function Config() {}

  Config.proxy_image_url = 'http://www.google.com/puppies.jpg';

  return Config;

})();
