// Generated by CoffeeScript 1.3.1
(function() {
  var Config;

  Config = (function() {

    Config.name = 'Config';

    function Config() {}

    Config.PROXY_IMAGE_URL = 'http://www.google.com/puppies.jpg';

    Config.SCROLL_SENSITIVITY = .001;

    Config.PAN_SENSITIVITY = 0.005;

    return Config;

  })();

}).call(this);
