<<<<<<< HEAD
=======
// Generated by CoffeeScript 1.3.3
>>>>>>> 269f5b2c977396d93bd200938c17209b42f4aee5
var Config;

Config = (function() {

  function Config() {}

  Config.proxy_image_url = 'http://www.google.com/puppies.jpg';

  /*
  	Create a texture within init and set it to Config.proxy_default_texture
  */

<<<<<<< HEAD
  Config.proxy_default_texture = null;

  Config.scroll_sensitivity = .001;

  Config.pan_sensitivity = 0.005;

  return Config;

=======

  Config.proxy_default_texture = null;

  Config.scroll_sensitivity = .001;

  Config.pan_sensitivity = 0.005;

  return Config;

>>>>>>> 269f5b2c977396d93bd200938c17209b42f4aee5
})();
