// Generated by CoffeeScript 1.3.2
var Projection,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Projection = (function() {

  function Projection() {
    this.getHeader = __bind(this.getHeader, this);

  }

  Projection.prototype.getHeader = function(image) {
    var avm;
    avm = new AVM("test")
	avm.load(loaded)
	function loaded(obj){
		var str = ' ';
		var i = 0;
		for(var key in obj.tags){
			str += (key + ' = ' + obj.tags[key]+'\n');
			i++;
		}
		if(i == 0)
			str = "no tags";
			
		console.log(str);
	}	
	
  };

  return Projection;

})();
