// Generated by CoffeeScript 1.3.2
var SkyView,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

SkyView = (function(_super) {

  __extends(SkyView, _super);

  SkyView.HTM = 0;

  SkyView.rotation = null;

  SkyView.translation = null;

  SkyView.renderMode = 0;

  SkyView.Math = null;

  function SkyView(options) {
    this.mousePress = __bind(this.mousePress, this);

    this.keyPressed = __bind(this.keyPressed, this);

    this.render = __bind(this.render, this);

    this.getPoint = __bind(this.getPoint, this);

    this.getLevel = __bind(this.getLevel, this);

    this.getScale = __bind(this.getScale, this);
    SkyView.__super__.constructor.call(this, options);
    this.Math = new math();
    this.level = 0;
    this.HTM = new HTM(this.level, this.gl, this.Math);
    this.rotation = [0.0, 0.0, 0.0];
    this.translation = [0.0, 0.0, 0.0];
    this.renderMode = this.gl.TRIANGLES;
    this.render();
  }

  SkyView.prototype.getScale = function() {
    return (180.0 * (1.0 - this.translation[2])) / 2;
  };

  SkyView.prototype.getLevel = function() {
    return 180.0 / (Math.pow(2, this.level + 1));
  };

  SkyView.prototype.getPoint = function(vert) {
    var denom, p_dp, p_prime;
    denom = Math.abs(vert[0]) + Math.abs(vert[1]) + Math.abs(vert[2]);
    p_prime = [vert[0] / denom, vert[1] / denom, vert[2] / denom];
    p_dp = [0.0, 0.0];
    if (p_prime[1] >= 0) {
      p_dp = [p_prime[0], p_prime[2]];
    } else {
      p_dp = [Math.sin(p_prime[0]) * (1 - Math.sin(p_prime[2])) * p_prime[2], Math.sin(p_prime[2]) * (1 - Math.sin(p_prime[0])) * p_prime[0]];
    }
    return p_dp;
  };

  SkyView.prototype.render = function() {
    var ctx, octamap, tri, triangle, vert, _i, _j, _len, _len1;
    this.preRender();
    this.HTM.bind(this.gl, this.shaderProgram);
    this.postRender(this.rotation, this.translation);
    this.HTM.render(this.gl, this.renderMode);
    octamap = document.getElementById('octamap');
    ctx = octamap.getContext('2d');
    ctx.fillRect(0, 0, 500, 500);
    tri = this.HTM.getTriangles();
    for (_i = 0, _len = tri.length; _i < _len; _i++) {
      triangle = tri[_i];
      for (_j = 0, _len1 = triangle.length; _j < _len1; _j++) {
        vert = triangle[_j];
        console.log(this.getPoint(vert));
      }
    }
  };

  SkyView.prototype.keyPressed = function(key) {
    switch (String.fromCharCode(key.which)) {
      case 'i':
        this.rotation[0]++;
        break;
      case 'k':
        this.rotation[0]--;
        break;
      case 'l':
        this.rotation[1]++;
        break;
      case 'j':
        this.rotation[1]--;
        break;
      case 'w':
        this.translation[2] += 0.1;
        break;
      case 's':
        this.translation[2] -= 0.1;
        break;
      case '0':
        this.HTM = new HTM(0, this.gl, this.Math);
        break;
      case '1':
        this.HTM = new HTM(1, this.gl, this.Math);
        break;
      case '2':
        this.HTM = new HTM(2, this.gl, this.Math);
        break;
      case '3':
        this.HTM = new HTM(3, this.gl, this.Math);
        break;
      case '4':
        this.HTM = new HTM(4, this.gl, this.Math);
        break;
      case '5':
        this.HTM = new HTM(5, this.gl, this.Math);
        break;
      case '6':
        this.HTM = new HTM(6, this.gl, this.Math);
        break;
      case '7':
        this.HTM = new HTM(7, this.gl, this.Math);
        break;
      case '8':
        this.HTM = new HTM(8, this.gl, this.Math);
    }
    this.render();
  };

  SkyView.prototype.mousePress = function(key) {
    var dir, far, inverse, it, matrices, names, near, origin, success, tri, triangle, _i, _len;
    matrices = this.getMatrices();
    near = [];
    far = [];
    success = GLU.unProject(key.x, this.gl.viewportHeight - key.y, 0.0, matrices[0], matrices[1], matrices[2], near);
    success = GLU.unProject(key.x, this.gl.viewportHeight - key.y, 1.0, matrices[0], matrices[1], matrices[2], far);
    dir = this.Math.subtract(far, near);
    origin = [0.0, 0.0, 0.0, 1.0];
    inverse = mat4.set(matrices[0], mat4.create());
    inverse = mat4.inverse(inverse);
    origin = this.Math.multiply(origin, inverse);
    dir = this.Math.norm(dir);
    tri = this.HTM.getTriangles();
    names = this.HTM.getNames();
    it = -1;
    for (_i = 0, _len = tri.length; _i < _len; _i++) {
      triangle = tri[_i];
      it = it + 1;
      if (this.Math.intersectTri(origin, dir, triangle)) {
        alert(names[it]);
        break;
      } else {
        console.log(triangle);
      }
    }
  };

  return SkyView;

})(WebGL);
